# prisma-project/docker-compose.yml
version: '3.9'
services:
  app:
    image: gmbt/delinder:latest
    container_name: delinder
    restart: always
    ports:
      - "80:8000"
    environment:
      NODE_ENV: production
  db:
    image: postgres
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data